maximum_length_name: 50
maximum_length_email: 255
minimum_length_password: 6
size_gravatar: 80
remember_me : "1"
per_page: 10
micropost_maximum_length_content: 140
per_page_micropost: 5
per_page_feed: 5
picture_size: 1
picture_x: 400
picture_y: 400
error_image_size: "Image is than 1MB"
gravatar_size_html: 50
accept_picture: "image/jpeg,image/gif,image/png"
